"""Learning report router — GPT-4o learning report generation."""

import logging
from fastapi import APIRouter, HTTPException
from app.models import LearningReportRequest, LearningReportResult

router = APIRouter(prefix="/learning", tags=["learning"])
logger = logging.getLogger(__name__)

LEARNING_REPORT_SYSTEM_PROMPT = """You are an expert educational content analyst. Generate a comprehensive learning report from the video transcript.

Return a JSON object with this structure:
{
  "learning_outcomes": ["What the viewer will learn from this video"],
  "key_concepts": [{"concept": "name", "definition": "clear definition", "timestamp": 0.0}],
  "key_facts": ["Important facts mentioned in the video"],
  "action_items": ["Practical actions the viewer should take after watching"],
  "misconceptions": [{"misconception": "common wrong belief", "correction": "the correct understanding"}],
  "next_topics": ["Related topics to explore next"],
  "prerequisites": ["Topics that should be understood before this video"]
}

Rules:
- Learning outcomes should start with "You will be able to..."
- Key concepts should include timestamps when first mentioned
- Action items should be specific and actionable
- Misconceptions should address common misunderstandings
- Next topics should logically follow from this video's content
- Return ONLY valid JSON"""


@router.post("/generate")
async def generate_learning_report(request: LearningReportRequest):
    """Generate a learning report from video transcript using GPT-4o."""
    return {
        "video_id": request.video_id,
        "message": "Learning report will be generated by the analyzer service using GPT-4o.",
    }


@router.get("/schema")
async def get_learning_report_schema():
    """Get the expected JSON schema for learning reports."""
    return {
        "schema": {
            "learning_outcomes": "string[]",
            "key_concepts": [{"concept": "string", "definition": "string", "timestamp": "float"}],
            "key_facts": "string[]",
            "action_items": "string[]",
            "misconceptions": [{"misconception": "string", "correction": "string"}],
            "next_topics": "string[]",
            "prerequisites": "string[]",
        }
    }
