"""Quiz router — GPT-4o quiz generation."""

import json
import logging
from fastapi import APIRouter, HTTPException
from app.models import (
    QuizGenerateRequest, QuizResponse, QuizQuestionModel,
    QuestionType, Difficulty, QuizAttemptResponse,
)

router = APIRouter(prefix="/quiz", tags=["quiz"])
logger = logging.getLogger(__name__)

QUIZ_SYSTEM_PROMPT = """You are an expert quiz creator. Generate a quiz based on the provided video transcript.

Return a JSON object with this structure:
{
  "title": "Quiz: [Video Title]",
  "questions": [
    {
      "question_index": 0,
      "question_type": "mcq|true_false|short_answer",
      "question_text": "The question",
      "options": ["option A", "option B", "option C", "option D"],  // only for mcq
      "correct_answer": "the correct answer",
      "explanation": "why this is correct",
      "difficulty": "easy|medium|hard"
    }
  ]
}

Rules:
- For MCQ: provide exactly 4 options
- For true_false: correct_answer must be "True" or "False"
- For short_answer: correct_answer should be a concise expected answer
- Questions should test understanding, not just memorization
- Include explanations for all questions
- Mix question types if multiple types are requested
- Return ONLY valid JSON"""


@router.post("/generate")
async def generate_quiz(request: QuizGenerateRequest):
    """Generate a quiz from video transcript using GPT-4o."""
    return {
        "video_id": request.video_id,
        "num_questions": request.num_questions,
        "difficulty": request.difficulty.value,
        "question_types": [qt.value for qt in request.question_types],
        "message": "Quiz will be generated by the analyzer service using GPT-4o.",
    }


@router.post("/attempt")
async def submit_quiz_attempt(
    quiz_id: str,
    user_id: str,
    answers: dict,
    time_taken_seconds: int = 0,
):
    """Submit a quiz attempt and calculate score."""
    if not answers:
        raise HTTPException(status_code=400, detail="No answers provided")

    # Scoring is done by comparing answers to correct answers in Supabase
    return {
        "quiz_id": quiz_id,
        "user_id": user_id,
        "message": "Quiz attempt will be scored by querying correct answers from Supabase.",
    }


@router.get("/schema")
async def get_quiz_schema():
    """Get the expected JSON schema for quiz generation."""
    return {
        "schema": {
            "title": "string",
            "questions": [
                {
                    "question_index": "int",
                    "question_type": "mcq|true_false|short_answer",
                    "question_text": "string",
                    "options": "string[] (mcq only)",
                    "correct_answer": "string",
                    "explanation": "string",
                    "difficulty": "easy|medium|hard",
                }
            ],
        }
    }
