"""Thumbnails router — DALL-E 3 thumbnail generation."""

import logging
from fastapi import APIRouter, HTTPException
from app.models import ThumbnailStyle, ThumbnailRegenerateRequest

router = APIRouter(prefix="/thumbnails", tags=["thumbnails"])
logger = logging.getLogger(__name__)

THUMBNAIL_STYLE_PROMPTS = {
    ThumbnailStyle.YOUTUBE_CREATOR: "Create a YouTube-style thumbnail with bold, expressive text overlay, high saturation colors, surprised/excited facial expression area, and dramatic lighting. 16:9 aspect ratio.",
    ThumbnailStyle.CINEMATIC: "Create a cinematic thumbnail with dramatic lighting, film grain texture, shallow depth of field, moody color grading, and professional composition. 16:9 aspect ratio.",
    ThumbnailStyle.EDUCATIONAL: "Create an educational thumbnail with clean layout, readable text, icons or diagrams, bright but professional colors, and clear visual hierarchy. 16:9 aspect ratio.",
    ThumbnailStyle.MINIMAL: "Create a minimal thumbnail with lots of negative space, simple typography, muted color palette, and a single focal point. 16:9 aspect ratio.",
    ThumbnailStyle.HIGH_CONTRAST: "Create a high-contrast thumbnail with bold black and white elements, vibrant accent colors, large text, and striking visual impact. 16:9 aspect ratio.",
    ThumbnailStyle.EDITORIAL: "Create an editorial-style thumbnail with magazine-quality composition, sophisticated typography, balanced color palette, and professional photography aesthetic. 16:9 aspect ratio.",
}


@router.post("/generate")
async def generate_thumbnails(
    video_id: str,
    title: str,
    summary: str = "",
    styles: list[ThumbnailStyle] = None,
):
    """Generate thumbnails using DALL-E 3.

    This endpoint defines the API contract. The actual generation
    is performed by the thumbnail_generator service.
    """
    if not styles:
        styles = list(ThumbnailStyle)

    if len(styles) > 6:
        raise HTTPException(status_code=400, detail="Maximum 6 thumbnail styles allowed")

    return {
        "video_id": video_id,
        "title": title,
        "styles_requested": [s.value for s in styles],
        "message": "Thumbnails will be generated by the thumbnail_generator service using DALL-E 3.",
        "style_prompts": {s.value: THUMBNAIL_STYLE_PROMPTS.get(s, "") for s in styles},
    }


@router.post("/regenerate")
async def regenerate_thumbnails(request: ThumbnailRegenerateRequest):
    """Regenerate thumbnails for a video with specified styles."""
    return await generate_thumbnails(
        video_id=request.video_id,
        title="",  # Title will be fetched from Supabase
        styles=request.styles,
    )


@router.get("/styles")
async def get_thumbnail_styles():
    """Get available thumbnail styles."""
    return {
        "styles": [
            {"value": s.value, "label": s.value.replace("_", " ").title(), "prompt": THUMBNAIL_STYLE_PROMPTS.get(s, "")}
            for s in ThumbnailStyle
        ]
    }
